# Generated by Django 4.2.16 on 2024-11-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='user_guess',
            field=models.IntegerField(null=True),
        ),
    ]
