# Generated by Django 4.2.11 on 2024-09-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_description',
            field=models.TextField(blank=True),
        ),
    ]
